apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'caddy'
        static_configs:
          - targets: ['caddy-metrics.caddy-system.svc.cluster.local:9765']
      
      - job_name: 'mysql-exporter'
        static_configs:
          - targets: ['mysql-exporter-service.testing.svc.cluster.local:9104']
        
      - job_name: 'fastapi'
        static_configs:
          - targets: ['fastapi-simple-server-service.testing.svc.cluster.local:8000']
        
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']